### ISSUE TITLE
MPIR 3.0.0: Fat Build on Win64

### ISSUE THREAD

**Issue by duhadler** [wbhart/mpir#213]
While a fat build on Win64 works fine for MPIR 2.7.2, there seems to be an issue with MPIR 3.0.0 (see below for details). Everything is fine with the fat build on Win32, and the fat build compiles without problems on Win64.  There are no issues with make check on Win64  if a specific processor (on my machine haswell) is chosen on Win64. 

The following make check error message for a fat build on Win64 suggests a problem with telling the haswell, sandybridge and skylake code apart. Any help would be much appreciated!

```
$ make check
make  check-recursive
make[1]: Entering directory '/home/MP64/mpir-3.0.0'
Making check in tests
make[2]: Entering directory '/home/MP64/mpir-3.0.0/tests'
Making check in .
make[3]: Entering directory '/home/MP64/mpir-3.0.0/tests'
make  libtests.la t-bswap.exe t-constants.exe t-count_zeros.exe t-gmpmax.exe t-hightomask.exe t-modlinv.exe t-parity.exe t-popc.exe t-sub.exe
make[4]: Entering directory '/home/MP64/mpir-3.0.0/tests'
make[4]: 'libtests.la' is up to date.
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99  -m64 -march=k8 -Wno-attributes   -o t-bswap.exe t-bswap.o libtests.la ../libmpir.la
libtool: link: gcc -std=gnu99 -m64 -march=k8 -Wno-attributes -o t-bswap.exe t-bswap.o  ./.libs/libtests.a /home/MP64/mpir-3.0.0/.libs/libmpir.a ../.libs/libmpir.a
C:/Extra/mpFormulaTDM/ExternalTools/msys32/home/MP64/mpir-3.0.0/.libs/libmpir.a(haswell_sqr_basecase.o):haswell_sqr_basecase.as:(.text+0x60): multiple definition of `__gmpn_sqr_basec1'
C:/Extra/mpFormulaTDM/ExternalTools/msys32/home/MP64/mpir-3.0.0/.libs/libmpir.a(skylake_sqr_basecase.o):skylake_sqr_basecase.as:(.text+0x60): first defined here
C:/Extra/mpFormulaTDM/ExternalTools/msys32/home/MP64/mpir-3.0.0/.libs/libmpir.a(haswell_redc_1.o):haswell_redc_1.as:(.text+0xa): multiple definition of `__g?mpn_sandybridge_redc_1'
C:/Extra/mpFormulaTDM/ExternalTools/msys32/home/MP64/mpir-3.0.0/.libs/libmpir.a(skylake_redc_1.o):skylake_redc_1.as:(.text+0xa): first defined here
C:/Extra/mpFormulaTDM/ExternalTools/msys32/home/MP64/mpir-3.0.0/.libs/libmpir.a(haswell_mul_1.o):haswell_mul_1.as:(.text+0x13): multiple definition of `__g?mpn_sandybridge_mul'
C:/Extra/mpFormulaTDM/ExternalTools/msys32/home/MP64/mpir-3.0.0/.libs/libmpir.a(skylake_mul_1.o):skylake_mul_1.as:(.text+0x13): first defined here
C:/Extra/mpFormulaTDM/ExternalTools/msys32/home/MP64/mpir-3.0.0/.libs/libmpir.a(sandybridge_redc_1.o):sandybridge_redc_1.as:(.text+0xa): multiple definition of `__g?mpn_sandybridge_redc_1'
C:/Extra/mpFormulaTDM/ExternalTools/msys32/home/MP64/mpir-3.0.0/.libs/libmpir.a(skylake_redc_1.o):skylake_redc_1.as:(.text+0xa): first defined here
C:/Extra/mpFormulaTDM/ExternalTools/msys32/home/MP64/mpir-3.0.0/.libs/libmpir.a(sandybridge_mul_1.o):sandybridge_mul_1.as:(.text+0x13): multiple definition of `__g?mpn_sandybridge_mul'
C:/Extra/mpFormulaTDM/ExternalTools/msys32/home/MP64/mpir-3.0.0/.libs/libmpir.a(skylake_mul_1.o):skylake_mul_1.as:(.text+0x13): first defined here
collect2.exe: error: ld returned 1 exit status
Makefile:735: recipe for target 't-bswap.exe' failed
make[4]: *** [t-bswap.exe] Error 1
make[4]: Leaving directory '/home/MP64/mpir-3.0.0/tests'
Makefile:1165: recipe for target 'check-am' failed
make[3]: *** [check-am] Error 2
make[3]: Leaving directory '/home/MP64/mpir-3.0.0/tests'
Makefile:798: recipe for target 'check-recursive' failed
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory '/home/MP64/mpir-3.0.0/tests'
Makefile:942: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/MP64/mpir-3.0.0'
Makefile:1231: recipe for target 'check' failed
make: *** [check] Error 2

dietrichhadler@DIETRICHHADCC1D MINGW32 /home/MP64/mpir-3.0.0

```

**Comment by wbhart** [comment]
Thanks, I'll take a look into it. I don't immediately see the problem, and
it's going to take me a few days to fix it, as I'm travelling.

**Comment by wbhart** [comment]
We don't intend to support fat builds on MSYS going forward.
