### ISSUE TITLE
Clean up build system wrt mpn_preinv_divrem_1

### ISSUE THREAD

**Issue by wbhart** [wbhart/mpir#57]
Some functions such as mpn_preinv_divrem_1 have unusual hacks in the build system to decide whether native versions are available for certain architectures. These hacks seem to break from time-to-time and we need something more robust.

**Comment by jamesjer** [comment]
Fedora just did a mass rebuild with gcc 7, and mpir 2.7.2 failed to build on x86_64 and ppc64le.  In the x86_64 case, the failure was at the linking step, like so:

mpn/.libs/preinv_divrem_1.o: In function `__gmpn_preinv_divrem_1':
/builddir/build/BUILD/mpir-2.7.2/mpn/preinv_divrem_1.c:57: multiple definition of `__gmpn_preinv_divrem_1'
mpn/.libs/divrem_euclidean_qr_1.o:divrem_euclidean_qr_1.as:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status

Is that a manifestation of this issue?  If so, what went wrong, and how can I fix it?  (The ppc64le issue is different; the error message indicates that the assembly language files were compiled in big endian mode, and therefore fail to link with the little endian mode object files created from the C sources.  I'll try to figure that one out.)

**Comment by wbhart** [comment]
Usually you get this message from not building MPIR from a clean checkout.
I don't have any more specific information at this stage.

**Comment by wbhart** [comment]
I believe we dropped ppc as an explicitly supported platform.
